"""update user table

Revision ID: 34447d894283
Revises: f6f5ed193645
Create Date: 2016-05-07 15:17:42.035777

"""

# revision identifiers, used by Alembic.
revision = '34447d894283'
down_revision = 'f6f5ed193645'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'))
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=130),
               existing_nullable=False)
    op.drop_column('User', 'password_salt')
    op.alter_column('UserToInstitution', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_server_default=sa.text('nextval(\'"UserToInstitution_id_seq"\'::regclass)'))
    op.alter_column('UserToInstitution', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserToInstitution', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('UserToInstitution', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_server_default=sa.text('nextval(\'"UserToInstitution_id_seq"\'::regclass)'))
    op.add_column('User', sa.Column('password_salt', sa.VARCHAR(length=29), autoincrement=False, nullable=False))
    op.alter_column('User', 'password_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('User', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'))
    ### end Alembic commands ###
