"""add UserToInstitution

Revision ID: f6f5ed193645
Revises: 09e9ac9a446a
Create Date: 2016-04-05 00:52:24.567610

"""

# revision identifiers, used by Alembic.
revision = 'f6f5ed193645'
down_revision = '09e9ac9a446a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserToInstitution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserToInstitution')
    ### end Alembic commands ###
