"""empty message

Revision ID: 8a13c4f4b843
Revises: None
Create Date: 2016-03-04 13:05:28.071823

"""

# revision identifiers, used by Alembic.
revision = '8a13c4f4b843'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kittens', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kittens', 'modified')
    ### end Alembic commands ###
